# Generated by Django 4.2.4 on 2023-08-12 17:56


import django.db.models.deletion
from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def set_chat_message_levels(
    apps: Apps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    chat_message = apps.get_model("hunt", "ChatMessage")
    level = apps.get_model("hunt", "Level")
    for message in chat_message.objects.all():
        _, number = message.room.rsplit("_", 1)
        message.level = level.objects.get(number=number)
        message.save()


class Migration(migrations.Migration):
    dependencies = [
        ("hunt", "0004_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="level",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="hunt.level",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(set_chat_message_levels),
        migrations.RemoveField(
            model_name="chatmessage",
            name="room",
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="hunt.level",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="name",
            field=models.CharField(max_length=32),
        ),
    ]
