# Generated by Django 4.2.4 on 2023-08-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0005_remove_chatmessage_room_chatmessage_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
