# Generated by Django 4.2.5 on 2023-09-13 18:20
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hunt", "0006_alter_chatmessage_name"),
    ]

    operations = [
        migrations.RenameField("HuntEvent", "type", "kind"),
    ]
