# Generated by Django 5.2.10 on 2026-01-24 22:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0007_rename_event_type_to_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['team', 'level'], name='hunt_chatme_team_id_1959c2_idx'),
        ),
    ]
